### PR TITLE
Article VI

### PR DESCRIPTION
**Pull request by Cryptex-github**

### CODE REVIEW

**Comment by Cryptex-github** [comment]
@DistortedPumpkin I demand this section to be ratified as soon as possible.

**Comment by Inferno1679** [comment]
**a**

**Comment by jay3332** [comment]
LGTM

**Review by tazz4843 — APPROVED** [review]

**Review by goose1218 — APPROVED** [review]

**Review by DistortedPumpkin — APPROVED** [review]

**Review by DistortedPumpkin — APPROVED** [review]

**Comment by jay3332** [comment]
silly guy cryptex

**Pull request closed without merging**
